"""Migration description."""

# pylint: disable=no-member
"""Primeira criacao da tabela

Revision ID: 6671cc46dfb4
Revises: 
Create Date: 2026-03-28 12:18:30.823206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6671cc46dfb4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome_adm", sa.String(), nullable=False),
        sa.Column("senha", sa.String(), nullable=False),
        sa.Column("cargo", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_nome_adm"), "users", ["nome_adm"], unique=True)
    op.create_table(
        "cursos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(), nullable=False),
        sa.Column("descricao", sa.String(), nullable=False),
        sa.Column("id_instrutor", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_instrutor"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cursos_id"), "cursos", ["id"], unique=False)
    op.create_table(
        "matriculas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("progresso", sa.Float(), nullable=True),
        sa.Column("id_aluno", sa.Integer(), nullable=True),
        sa.Column("id_curso", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_aluno"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_curso"],
            ["cursos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_matriculas_id"), "matriculas", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_matriculas_id"), table_name="matriculas")
    op.drop_table("matriculas")
    op.drop_index(op.f("ix_cursos_id"), table_name="cursos")
    op.drop_table("cursos")
    op.drop_index(op.f("ix_users_nome_adm"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
