"""modularize database models

Revision ID: b3139e6ca591
Revises: 2e26543bc63f
Create Date: 2026-09-16 21:27:28.141053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3139e6ca591'
down_revision: Union[str, Sequence[str], None] = '2e26543bc63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('hired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_full_name'), 'employees', ['full_name'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('base_price >= 0', name='ck_product_price_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRATOR', 'MANAGER', name='accountrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number')
    )
    op.create_index(op.f('ix_cards_employee_id'), 'cards', ['employee_id'], unique=False)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_table('compensations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('HOURLY', 'MONTHLY', name='paymenttype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount >= 0', name='ck_compensation_amount_nonnegative'),
    sa.CheckConstraint('valid_until IS NULL OR valid_until > valid_from', name='ck_compensation_valid_period'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compensations_employee_id'), 'compensations', ['employee_id'], unique=False)
    op.create_table('current_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_in_stock', sa.Integer(), nullable=False),
    sa.Column('product_to_come', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('product_in_stock >=0', name='ck_product_non_negative'),
    sa.CheckConstraint('product_to_come >= 0', name='ck_product_to_come_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', name='uq_inventory_warehouse_product')
    )
    op.create_index(op.f('ix_current_inventory_id'), 'current_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_current_inventory_product_id'), 'current_inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_current_inventory_warehouse_id'), 'current_inventory', ['warehouse_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_employee_id', sa.Integer(), nullable=False),
    sa.Column('department_title', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['manager_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_manager_employee_id'), 'departments', ['manager_employee_id'], unique=False)
    op.create_table('monthly_payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('datetime_payment', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overtime_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_year', sa.Integer(), nullable=False),
    sa.Column('reference_month', sa.Integer(), nullable=False),
    sa.CheckConstraint('base_salary >= 0', name='ck_payroll_base_salary_nonnegative'),
    sa.CheckConstraint('overtime_pay >= 0', name='ck_payroll_overtime_nonnegative'),
    sa.CheckConstraint('reference_month BETWEEN 1 AND 12', name='ck_payroll_valid_month'),
    sa.CheckConstraint('reference_month BETWEEN 1 AND 12', name='ck_payroll_valid_month'),
    sa.CheckConstraint('tax_deductions >= 0', name='ck_payroll_deductions_nonnegative'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'reference_year', 'reference_month', name='uq_payroll_employee_period'),
    sa.UniqueConstraint('employee_id', 'reference_year', 'reference_month', name='uq_payroll_employee_period')
    )
    op.create_index(op.f('ix_monthly_payroll_employee_id'), 'monthly_payroll', ['employee_id'], unique=False)
    op.create_index(op.f('ix_monthly_payroll_id'), 'monthly_payroll', ['id'], unique=False)
    op.create_table('time_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('clock_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clock_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hour_worked', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.CheckConstraint('clock_out is NULL OR clock_out > clock_in', name='ck_time_valid_period'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_records_employee_id'), 'time_records', ['employee_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_account_id'), 'audit_logs', ['account_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_inventory_id', sa.Integer(), nullable=False),
    sa.Column('created_by_account_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('IN', 'OUT', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_at_transaction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_quantity_positive'),
    sa.CheckConstraint('unit_price_at_transaction >= 0', name='ck_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['current_inventory_id'], ['current_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_created_by_account_id'), 'inventory_movements', ['created_by_account_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_current_inventory_id'), 'inventory_movements', ['current_inventory_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_id'), 'inventory_movements', ['id'], unique=False)
    op.drop_index(op.f('ix_matriculas_id'), table_name='matriculas')
    op.drop_table('matriculas')
    op.drop_index(op.f('ix_cursos_id'), table_name='cursos')
    op.drop_table('cursos')
    op.drop_index(op.f('ix_aulas_id'), table_name='aulas')
    op.drop_table('aulas')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_nome_user'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('senha', sa.VARCHAR(), nullable=False),
    sa.Column('cargo', sa.VARCHAR(), nullable=False),
    sa.Column('nome_user', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_nome_user'), 'users', ['nome_user'], unique=1)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('aulas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(), nullable=False),
    sa.Column('caminho_arquivo', sa.VARCHAR(), nullable=False),
    sa.Column('id_curso', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aulas_id'), 'aulas', ['id'], unique=False)
    op.create_table('cursos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(), nullable=False),
    sa.Column('descricao', sa.VARCHAR(), nullable=False),
    sa.Column('id_instrutor', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_instrutor'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursos_id'), 'cursos', ['id'], unique=False)
    op.create_table('matriculas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('progresso', sa.FLOAT(), nullable=True),
    sa.Column('id_aluno', sa.INTEGER(), nullable=True),
    sa.Column('id_curso', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matriculas_id'), 'matriculas', ['id'], unique=False)
    op.drop_index(op.f('ix_inventory_movements_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_current_inventory_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_created_by_account_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_audit_logs_account_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_time_records_employee_id'), table_name='time_records')
    op.drop_table('time_records')
    op.drop_index(op.f('ix_monthly_payroll_id'), table_name='monthly_payroll')
    op.drop_index(op.f('ix_monthly_payroll_employee_id'), table_name='monthly_payroll')
    op.drop_table('monthly_payroll')
    op.drop_index(op.f('ix_departments_manager_employee_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_current_inventory_warehouse_id'), table_name='current_inventory')
    op.drop_index(op.f('ix_current_inventory_product_id'), table_name='current_inventory')
    op.drop_index(op.f('ix_current_inventory_id'), table_name='current_inventory')
    op.drop_table('current_inventory')
    op.drop_index(op.f('ix_compensations_employee_id'), table_name='compensations')
    op.drop_table('compensations')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_employee_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_full_name'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
