name: Testes Automatizados (CI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    # CRIAMOS UM ".ENV" FALSO SÓ PARA O ROBÔ USAR
    env:
      DATABASE_URL: "sqlite:///./test_temp.db"
      SECRET_KEY: "senha_secreta_temporaria_para_testes"

    steps:
    - name: Baixando o repositório
      uses: actions/checkout@v3

    - name: Configurando o Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Instalando dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodando o Pytest
      run: python -m pytest tests -q